### ISSUE TITLE
AudioPick randomly changes my default device

### ISSUE THREAD

**Issue by eddielucitt** [necropola/AudioPick#5]
Hi, not a complicated issue, but definitely an annoying one! Hoping to help solve this in any way I can! 

My copy of AudioPick changes my default device about once a day, and I have to manually go into the settings and re-select my default device (a virtual cable output) every time this happens.

**Comment by necropola** [comment]
- Does it change the global (AudioPick  Options) device or the device chosen for a specific tab? 
- Does it change while Chrome is running?
- Does it always switch to the same device?

I may have spotted a problem in the code that reads the value from chrome storage.

**Comment by eddielucitt** [comment]
- Yes, it changes it in the default options.
- I'm not sure, I don't think so. I think it happens when I restart Chrome. 
- No, it's a seemingly random device. Sometimes it defaults to NOTHING selected.

**Comment by necropola** [comment]
Moved to: https://github.com/rain-fighters/AudioPick/issues/5
